/*
 * Generated by gen-yagl-calls.py, do not modify!
 */
#include "yagl_host_egl_calls.h"
#include "yagl_transport_egl.h"
#include "yagl_state.h"
#include <assert.h>

/*
 * eglGetDisplay wrapper. id = 1
 */
yagl_host_handle yagl_host_eglGetDisplay(uint32_t display_id, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 1, 5 * 8, 5 * 8);
    yagl_transport_put_out_uint32_t(t, display_id);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglInitialize wrapper. id = 2
 */
EGLBoolean yagl_host_eglInitialize(yagl_host_handle dpy, EGLint *major, EGLint *minor, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 2, 9 * 8, 9 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_in_EGLint(t, major);
    yagl_transport_put_in_EGLint(t, minor);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglTerminate wrapper. id = 3
 */
EGLBoolean yagl_host_eglTerminate(yagl_host_handle dpy, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 3, 5 * 8, 5 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglGetConfigs wrapper. id = 4
 */
EGLBoolean yagl_host_eglGetConfigs(yagl_host_handle dpy, yagl_host_handle *configs, int32_t configs_maxcount, int32_t *configs_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 4, 7 * 8, 5 * 8 + yagl_transport_array_size(configs, configs_maxcount, sizeof(yagl_host_handle)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_in_array(t, configs, configs_maxcount, configs_count, sizeof(yagl_host_handle));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglChooseConfig wrapper. id = 5
 */
EGLBoolean yagl_host_eglChooseConfig(yagl_host_handle dpy, const EGLint *attrib_list, int32_t attrib_list_count, yagl_host_handle *configs, int32_t configs_maxcount, int32_t *configs_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 5, 9 * 8, 5 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)) + yagl_transport_array_size(configs, configs_maxcount, sizeof(yagl_host_handle)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_array(t, configs, configs_maxcount, configs_count, sizeof(yagl_host_handle));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglGetConfigAttrib wrapper. id = 6
 */
EGLBoolean yagl_host_eglGetConfigAttrib(yagl_host_handle dpy, yagl_host_handle config, EGLint attribute, EGLint *value, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 6, 9 * 8, 9 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_EGLint(t, attribute);
    yagl_transport_put_in_EGLint(t, value);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglDestroySurface wrapper. id = 7
 */
EGLBoolean yagl_host_eglDestroySurface(yagl_host_handle dpy, yagl_host_handle surface, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 7, 6 * 8, 6 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglQuerySurface wrapper. id = 8
 */
EGLBoolean yagl_host_eglQuerySurface(yagl_host_handle dpy, yagl_host_handle surface, EGLint attribute, EGLint *value, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 8, 9 * 8, 9 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_put_out_EGLint(t, attribute);
    yagl_transport_put_in_EGLint(t, value);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglBindAPI wrapper. id = 9
 */
void yagl_host_eglBindAPI(EGLenum api)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_egl, 9, 1 * 8, 1 * 8);
    yagl_transport_put_out_EGLenum(t, api);
    yagl_transport_end(t);
}

/*
 * eglWaitClient wrapper. id = 10
 */
void yagl_host_eglWaitClient()
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_egl, 10, 0 * 8, 0 * 8);
    yagl_transport_end(t);
    yagl_transport_flush(t, NULL);
}

/*
 * eglReleaseThread wrapper. id = 11
 */
EGLBoolean yagl_host_eglReleaseThread(EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 11, 4 * 8, 4 * 8);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglSurfaceAttrib wrapper. id = 12
 */
EGLBoolean yagl_host_eglSurfaceAttrib(yagl_host_handle dpy, yagl_host_handle surface, EGLint attribute, EGLint value, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 12, 8 * 8, 8 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_put_out_EGLint(t, attribute);
    yagl_transport_put_out_EGLint(t, value);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglCreateContext wrapper. id = 13
 */
yagl_host_handle yagl_host_eglCreateContext(yagl_host_handle dpy, yagl_host_handle config, yagl_host_handle share_context, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 13, 9 * 8, 7 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_yagl_host_handle(t, share_context);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglDestroyContext wrapper. id = 14
 */
EGLBoolean yagl_host_eglDestroyContext(yagl_host_handle dpy, yagl_host_handle ctx, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 14, 6 * 8, 6 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, ctx);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglMakeCurrent wrapper. id = 15
 */
void yagl_host_eglMakeCurrent(yagl_host_handle dpy, yagl_host_handle draw, yagl_host_handle read, yagl_host_handle ctx)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_egl, 15, 4 * 8, 4 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, draw);
    yagl_transport_put_out_yagl_host_handle(t, read);
    yagl_transport_put_out_yagl_host_handle(t, ctx);
    yagl_transport_end(t);
    yagl_transport_flush(t, NULL);
}

/*
 * eglQueryContext wrapper. id = 16
 */
EGLBoolean yagl_host_eglQueryContext(yagl_host_handle dpy, yagl_host_handle ctx, EGLint attribute, EGLint *value, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 16, 9 * 8, 9 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, ctx);
    yagl_transport_put_out_EGLint(t, attribute);
    yagl_transport_put_in_EGLint(t, value);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglSwapBuffers wrapper. id = 17
 */
void yagl_host_eglSwapBuffers(yagl_host_handle dpy, yagl_host_handle surface)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_egl, 17, 2 * 8, 2 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_end(t);
    yagl_transport_flush(t, NULL);
}

/*
 * eglCopyBuffers wrapper. id = 18
 */
void yagl_host_eglCopyBuffers(yagl_host_handle dpy, yagl_host_handle surface)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_egl, 18, 2 * 8, 2 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_end(t);
    yagl_transport_flush(t, NULL);
}

/*
 * eglCreateWindowSurfaceOffscreenYAGL wrapper. id = 19
 */
yagl_host_handle yagl_host_eglCreateWindowSurfaceOffscreenYAGL(yagl_host_handle dpy, yagl_host_handle config, uint32_t width, uint32_t height, uint32_t bpp, void *pixels, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 19, 12 * 8, 10 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_uint32_t(t, width);
    yagl_transport_put_out_uint32_t(t, height);
    yagl_transport_put_out_uint32_t(t, bpp);
    yagl_transport_put_out_va(t, pixels);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglCreatePbufferSurfaceOffscreenYAGL wrapper. id = 20
 */
yagl_host_handle yagl_host_eglCreatePbufferSurfaceOffscreenYAGL(yagl_host_handle dpy, yagl_host_handle config, uint32_t width, uint32_t height, uint32_t bpp, void *pixels, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 20, 12 * 8, 10 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_uint32_t(t, width);
    yagl_transport_put_out_uint32_t(t, height);
    yagl_transport_put_out_uint32_t(t, bpp);
    yagl_transport_put_out_va(t, pixels);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglCreatePixmapSurfaceOffscreenYAGL wrapper. id = 21
 */
yagl_host_handle yagl_host_eglCreatePixmapSurfaceOffscreenYAGL(yagl_host_handle dpy, yagl_host_handle config, uint32_t width, uint32_t height, uint32_t bpp, void *pixels, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 21, 12 * 8, 10 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_uint32_t(t, width);
    yagl_transport_put_out_uint32_t(t, height);
    yagl_transport_put_out_uint32_t(t, bpp);
    yagl_transport_put_out_va(t, pixels);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglResizeOffscreenSurfaceYAGL wrapper. id = 22
 */
EGLBoolean yagl_host_eglResizeOffscreenSurfaceYAGL(yagl_host_handle dpy, yagl_host_handle surface, uint32_t width, uint32_t height, uint32_t bpp, void *pixels, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 22, 10 * 8, 10 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_put_out_uint32_t(t, width);
    yagl_transport_put_out_uint32_t(t, height);
    yagl_transport_put_out_uint32_t(t, bpp);
    yagl_transport_put_out_va(t, pixels);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglCreateWindowSurfaceOnscreenYAGL wrapper. id = 23
 */
yagl_host_handle yagl_host_eglCreateWindowSurfaceOnscreenYAGL(yagl_host_handle dpy, yagl_host_handle config, yagl_winsys_id win, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 23, 9 * 8, 7 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_yagl_winsys_id(t, win);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglCreatePbufferSurfaceOnscreenYAGL wrapper. id = 24
 */
yagl_host_handle yagl_host_eglCreatePbufferSurfaceOnscreenYAGL(yagl_host_handle dpy, yagl_host_handle config, yagl_winsys_id buffer, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 24, 9 * 8, 7 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_yagl_winsys_id(t, buffer);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglCreatePixmapSurfaceOnscreenYAGL wrapper. id = 25
 */
yagl_host_handle yagl_host_eglCreatePixmapSurfaceOnscreenYAGL(yagl_host_handle dpy, yagl_host_handle config, yagl_winsys_id pixmap, const EGLint *attrib_list, int32_t attrib_list_count, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    yagl_host_handle retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 25, 9 * 8, 7 * 8 + yagl_transport_array_size(attrib_list, attrib_list_count, sizeof(EGLint)));
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, config);
    yagl_transport_put_out_yagl_winsys_id(t, pixmap);
    yagl_transport_put_out_array(t, attrib_list, attrib_list_count, sizeof(EGLint));
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_yagl_host_handle(t, &retval);
    yagl_transport_end(t);

    return retval;
}

/*
 * eglInvalidateOnscreenSurfaceYAGL wrapper. id = 26
 */
void yagl_host_eglInvalidateOnscreenSurfaceYAGL(yagl_host_handle dpy, yagl_host_handle surface, yagl_winsys_id buffer)
{
    struct yagl_transport *t = yagl_get_transport();

    yagl_transport_begin(t, yagl_api_id_egl, 26, 3 * 8, 3 * 8);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_host_handle(t, surface);
    yagl_transport_put_out_yagl_winsys_id(t, buffer);
    yagl_transport_end(t);
    yagl_transport_flush(t, NULL);
}

/*
 * eglCreateImageYAGL wrapper. id = 27
 */
EGLBoolean yagl_host_eglCreateImageYAGL(uint32_t texture, yagl_host_handle dpy, yagl_winsys_id buffer, EGLint *error)
{
    struct yagl_transport *t = yagl_get_transport();
    EGLBoolean retval = 0;

    yagl_transport_begin(t, yagl_api_id_egl, 27, 7 * 8, 7 * 8);
    yagl_transport_put_out_uint32_t(t, texture);
    yagl_transport_put_out_yagl_host_handle(t, dpy);
    yagl_transport_put_out_yagl_winsys_id(t, buffer);
    yagl_transport_put_in_EGLint(t, error);
    yagl_transport_put_in_EGLBoolean(t, &retval);
    yagl_transport_end(t);

    return retval;
}
